name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: 'dotnet build'
        run: dotnet build

      - name: 'dotnet test'
        run: dotnet test
